Update compress

diff --git a/bin/steps/compress b/bin/steps/compress
--- a/bin/steps/compress
+++ b/bin/steps/compress
@@ -9,20 +9,16 @@ indent() {
 MANAGE_FILE=$(find . -maxdepth 3 -type f -name 'manage.py' | head -1)
 MANAGE_FILE=${MANAGE_FILE:-fakepath}
 
-[ -f .heroku/collectstatic_disabled ] && DISABLE_COMRPESS=1
 
-if [ ! "DISABLE_COMRPESS" ] && [ -f "$MANAGE_FILE" ]; then
-    set +e
+set +e
 
-    echo "running compression"
-    python $MANAGE_FILE compress 2>&1 | indent
+echo "running compression"
+python $MANAGE_FILE compress 2>&1 | indent
 
-    [ $? -ne 0 ] && {
-        echo " !     Error running manage.py compress."
-    }
-
-    echo
+[ $? -ne 0 ] && {
+    echo " !     Error running manage.py compress."
+}
 
 
-fi
+
 
